### ISSUE TITLE
Publish to Gallery

### ISSUE THREAD

**Issue by michaeltlombardi** [DSorlov/Sorlov.PowerShell#1]
Now that the code itself is available, it'd be awesome to be able to get the module into the [gallery](https://www.powershellgallery.com/) so other modules can depend on it.

**Comment by michaeltlombardi** [comment]
Prior to gallery publish, pushing a release to this repo might be a good stopgap.

**Comment by DSorlov** [comment]
Good suggestion, now published to the Gallery also. See:
https://www.powershellgallery.com/packages/Sorlov.PowerShell/5.0.0.0
