### ISSUE TITLE
minikube startup error

### ISSUE THREAD

**Issue by ghost** [DSorlov/Sorlov.PowerShell#3]
Hi!
This printout during startup  actually creates issues with minikube on Windows with hyper-v
"
Windows PowerShell (with Sorlov.PowerShell v4.5.0.1)
Enhancements copyright (C) 2013 Daniel Sörlöv. All rights reserved.
"
Probably a issue with the minikube checks.. but I just wanted to let you know.

Thanks

**Comment by DSorlov** [comment]
This is because the module announces itself; if I remember correctly it could be supressed. I will look into this when I can find time. I will gladly accept any code contributions however.

**Comment by DSorlov** [comment]
@kogant Yepp, just had to check, but if you change the PrintBanner=$true; to PrintBanner=$false; in the psd the shell will not output the banner for silent operations.
